# Generated by Django 3.2.7 on 2022-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSchedulerBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroomparameter',
            name='unique_classroom_parameter',
        ),
        migrations.RemoveConstraint(
            model_name='coursetimeparameter',
            name='unique_course_time_parameter',
        ),
        migrations.RemoveConstraint(
            model_name='scheduledcourse',
            name='unique_scheduled_course',
        ),
        migrations.RemoveConstraint(
            model_name='semesterparameter',
            name='unique_semester_parameter',
        ),
        migrations.RemoveConstraint(
            model_name='teaches',
            name='unique_teaches',
        ),
        migrations.RemoveConstraint(
            model_name='usergroupclassparameter',
            name='unique_user_group_class_parameter',
        ),
        migrations.RemoveConstraint(
            model_name='usertimeparameter',
            name='unique_user_time_parameter',
        ),
        migrations.RenameField(
            model_name='classroomparameter',
            old_name='classroom_obj',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='classroomparameter',
            old_name='course_obj',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='classroomparameter',
            old_name='parameter_obj',
            new_name='parameter_id',
        ),
        migrations.RenameField(
            model_name='coursetimeparameter',
            old_name='course_obj',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='coursetimeparameter',
            old_name='parameter_obj',
            new_name='parameter_id',
        ),
        migrations.RenameField(
            model_name='coursetimeparameter',
            old_name='time_slot_obj',
            new_name='time_slot_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='classroom_obj',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='course_obj',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='schedule_obj',
            new_name='schedule_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='semester_obj',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='time_slot_obj',
            new_name='time_slot_id',
        ),
        migrations.RenameField(
            model_name='scheduledcourse',
            old_name='user_obj',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='semesterparameter',
            old_name='course_obj',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='semesterparameter',
            old_name='parameter_obj',
            new_name='parameter_id',
        ),
        migrations.RenameField(
            model_name='semesterparameter',
            old_name='semester_obj',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='course_obj',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='semester_obj',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='user_obj',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='day_time_obj',
            new_name='day_time_id',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='week_day_obj',
            new_name='week_day_id',
        ),
        migrations.RenameField(
            model_name='usergroupclassparameter',
            old_name='parameter_obj',
            new_name='parameter_id',
        ),
        migrations.RenameField(
            model_name='usergroupclassparameter',
            old_name='user_obj',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usertimeparameter',
            old_name='parameter_obj',
            new_name='parameter_id',
        ),
        migrations.RenameField(
            model_name='usertimeparameter',
            old_name='time_slot_obj',
            new_name='time_slot_id',
        ),
        migrations.RenameField(
            model_name='usertimeparameter',
            old_name='user_obj',
            new_name='user_id',
        ),
        migrations.AddConstraint(
            model_name='classroomparameter',
            constraint=models.UniqueConstraint(fields=('parameter_id', 'course_id', 'classroom_id'), name='unique_classroom_parameter'),
        ),
        migrations.AddConstraint(
            model_name='coursetimeparameter',
            constraint=models.UniqueConstraint(fields=('parameter_id', 'course_id', 'time_slot_id'), name='unique_course_time_parameter'),
        ),
        migrations.AddConstraint(
            model_name='parameterdata',
            constraint=models.UniqueConstraint(fields=('parameter_id', 'approved', 'requirement'), name='unique_parameter_data'),
        ),
        migrations.AddConstraint(
            model_name='scheduledcourse',
            constraint=models.UniqueConstraint(fields=('schedule_id', 'user_id', 'course_id', 'time_slot_id', 'semester_id', 'classroom_id'), name='unique_scheduled_course'),
        ),
        migrations.AddConstraint(
            model_name='semesterparameter',
            constraint=models.UniqueConstraint(fields=('parameter_id', 'course_id', 'semester_id'), name='unique_semester_parameter'),
        ),
        migrations.AddConstraint(
            model_name='teaches',
            constraint=models.UniqueConstraint(fields=('user_id', 'course_id', 'semester_id'), name='unique_teaches'),
        ),
        migrations.AddConstraint(
            model_name='usergroupclassparameter',
            constraint=models.UniqueConstraint(fields=('user_id', 'parameter_id'), name='unique_user_group_class_parameter'),
        ),
        migrations.AddConstraint(
            model_name='usertimeparameter',
            constraint=models.UniqueConstraint(fields=('user_id', 'parameter_id', 'time_slot_id'), name='unique_user_time_parameter'),
        ),
    ]
