# Generated by Django 3.2.8 on 2022-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSchedulerBackend', '0002_auto_20220323_2051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parameterdata',
            name='unique_parameter_data',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='Section',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='courseGroup',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
