# Generated by Django 3.2.8 on 2022-11-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSchedulerBackend', '0003_auto_20221125_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdata',
            name='semester_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassSchedulerBackend.semester'),
        ),
    ]
