# Generated by Django 3.2.8 on 2023-04-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassSchedulerBackend', '0004_parameterdata_semester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teaching_days', models.IntegerField(default=None)),
                ('parameter_id', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='ClassSchedulerBackend.parameterdata')),
                ('user_id', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_parameter',
            },
        ),
        migrations.AddConstraint(
            model_name='teachingparameter',
            constraint=models.UniqueConstraint(
                fields=('user_id', 'parameter_id'), name='unique_teaching_parameter'),
        ),
    ]
